### ISSUE TITLE
No results?

### ISSUE THREAD

**Issue by ghost** [Tux/speedtest#11]
Maybe I'm doing something wrong, but when I execute the speedtest script I don't get any test results. 

`speedtest.pl -P > c:\speedtest\speedtestresults.bat`

Outputs the following

`<?xml version="1.0" encoding="UTF-8" ?>
<prtg>
  <text>Testing from tw telecom holdings (206.x.x.x)</text>
  </prtg>`

**Comment by Tux** [comment]
Looks like you edited the IP after you posted the issue, as I got something else in my mail.
It might be that you use IPv6 instead of IPv4, and maybe speedtest does not cope. I have no idea.
Did you already try upping verbosity? `speedtest -Q -v9` should show you what is going on.
I just noted that `-P` does not support `-v9` (yet). I'd have to look into that

**Comment by doubleosixandahalf** [comment]
Yes I did remove my IP. I'm using an IPv4 public IP address so that should not be an issue. 

When I run `speedtest -Q -v9` the script stops after `Finding fastest host out of 7800 hosts for ...`

**Comment by Tux** [comment]
Does `speedtest -l` work? And if it does, could you pick the ID of the top one and use that as the selected server as in `speedtest -Q -s 1234` (assuming 1234 is the first ID in your list)
If there is no list at all, maybe speedtest is having difficulties in determining your country or location in general. What is your location, like what city do you work from? You can use that information to force speedtest to pick a country, like in `speedtest -l -c AZ` for Azerbaijan.

**Comment by Tux** [comment]
Closed due to lack of feedback
